package dev.tggamesyt;

import com.intellij.execution.BeforeRunTask;
import com.intellij.execution.RunManagerEx;
import com.intellij.execution.RunManagerListener;
import com.intellij.execution.RunnerAndConfigurationSettings;
import com.intellij.execution.configurations.RunConfiguration;
import com.intellij.openapi.application.ApplicationManager;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.startup.StartupActivity;
import org.jetbrains.annotations.NotNull;

import java.util.ArrayList;
import java.util.List;

public class MinecraftProjectStartupActivity implements StartupActivity.DumbAware {

    @Override
    public void runActivity(@NotNull Project project) {
        MinecraftOAuthConfigurable.project = project;

        // The "Minecraft Client" run configuration is often generated by the Minecraft Dev plugin a
        // little after the project opens (once Gradle import finishes), so handling it only once at
        // startup can miss it. Listen for run-configuration changes and, whenever the client config
        // appears or changes, make sure our before-run hook is attached and the args are current.
        project.getMessageBus().connect().subscribe(RunManagerListener.TOPIC, new RunManagerListener() {
            @Override
            public void runConfigurationAdded(@NotNull RunnerAndConfigurationSettings settings) {
                handle(settings);
            }

            @Override
            public void runConfigurationChanged(@NotNull RunnerAndConfigurationSettings settings) {
                handle(settings);
            }

            private void handle(RunnerAndConfigurationSettings settings) {
                if (isClientConfig(settings)) {
                    ensureBeforeRunTask(project, settings.getConfiguration());
                    MinecraftRunConfigUpdater.updateArgs();
                }
            }
        });

        // Attach the before-run hook to any client config that already exists, and apply args.
        ApplicationManager.getApplication().invokeLater(() -> {
            for (RunnerAndConfigurationSettings settings : RunManagerEx.getInstanceEx(project).getAllSettings()) {
                if (isClientConfig(settings)) {
                    ensureBeforeRunTask(project, settings.getConfiguration());
                }
            }
        });

        // Refresh any expired tokens in the background, then wire up the run config.
        ApplicationManager.getApplication().executeOnPooledThread(() -> {
            MinecraftAccountsState state = MinecraftAccountsState.getInstance();
            MinecraftOAuthManager manager = new MinecraftOAuthManager();

            // Make sure an account is selected so the first launch already has credentials.
            MinecraftRunConfigUpdater.selectedAccount();

            // Only attempt silent refreshes if the auth servers are actually reachable.
            if (MinecraftOAuthManager.areAuthServersUp()) {
                state.accounts.stream()
                        .filter(a -> a.isExpired() && a.canRefresh())
                        .forEach(manager::refreshAccount);
            }

            MinecraftRunConfigUpdater.updateArgs();
        });
    }

    private static boolean isClientConfig(RunnerAndConfigurationSettings settings) {
        return MinecraftRunConfigUpdater.getConfigName().equals(settings.getConfiguration().getName());
    }

    /** Adds the {@link MinecraftBeforeRunTask} to a configuration if it isn't already present. */
    private static void ensureBeforeRunTask(Project project, RunConfiguration config) {
        RunManagerEx rm = RunManagerEx.getInstanceEx(project);
        List<BeforeRunTask> tasks = new ArrayList<>(rm.getBeforeRunTasks(config));
        boolean alreadyPresent = tasks.stream().anyMatch(t -> t instanceof MinecraftBeforeRunTask);
        if (alreadyPresent) return;

        MinecraftBeforeRunTask task = new MinecraftBeforeRunTask();
        task.setEnabled(true);
        tasks.add(task);
        rm.setBeforeRunTasks(config, tasks);
    }
}
