package dev.tggamesyt;

import com.intellij.execution.RunManagerListener;
import com.intellij.execution.RunnerAndConfigurationSettings;
import com.intellij.openapi.application.ApplicationManager;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.startup.StartupActivity;
import org.jetbrains.annotations.NotNull;

public class MinecraftProjectStartupActivity implements StartupActivity.DumbAware {

    @Override
    public void runActivity(@NotNull Project project) {
        MinecraftOAuthConfigurable.project = project;

        // The "Minecraft Client" run configuration is often generated by the Minecraft Dev plugin
        // a little after the project opens (once Gradle import finishes), so updating the args once
        // at startup can miss it. Listen for run-configuration changes and (re)apply the selected
        // account whenever the client config appears or changes.
        project.getMessageBus().connect().subscribe(RunManagerListener.TOPIC, new RunManagerListener() {
            @Override
            public void runConfigurationAdded(@NotNull RunnerAndConfigurationSettings settings) {
                applyIfClientConfig(settings);
            }

            @Override
            public void runConfigurationChanged(@NotNull RunnerAndConfigurationSettings settings) {
                applyIfClientConfig(settings);
            }

            private void applyIfClientConfig(RunnerAndConfigurationSettings settings) {
                if (MinecraftRunConfigUpdater.getConfigName().equals(settings.getConfiguration().getName())) {
                    MinecraftRunConfigUpdater.updateArgs();
                }
            }
        });

        // Refresh any expired tokens in the background, then wire up the run config.
        ApplicationManager.getApplication().executeOnPooledThread(() -> {
            MinecraftAccountsState state = MinecraftAccountsState.getInstance();
            MinecraftOAuthManager manager = new MinecraftOAuthManager();

            // Make sure an account is selected so the first launch already has credentials.
            MinecraftRunConfigUpdater.selectedAccount();

            // Only attempt silent refreshes if the auth servers are actually reachable.
            // This avoids hammering offline endpoints (and, historically, spawning a browser
            // login tab per account when refresh failed). refreshAccount() never opens a browser.
            if (MinecraftOAuthManager.areAuthServersUp()) {
                state.accounts.stream()
                        .filter(a -> a.isExpired() && a.canRefresh())
                        .forEach(manager::refreshAccount);
            }

            MinecraftRunConfigUpdater.updateArgs();
        });
    }
}
